name: dalilak_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg:
  get_it: ^9.1.1
  modal_progress_hud_nsn: ^0.5.1
  carousel_slider:
  smooth_page_indicator: 1.1.0

  flutter_localizations:
    sdk: flutter

  intl: 0.20.2
  pin_code_fields: ^8.0.1
  flutter_bloc: ^9.1.1
  shared_preferences:
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get: ^4.7.2
  fl_chart: ^0.63.0
  percent_indicator: ^4.2.3
  flutter_credit_card: ^4.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # إضافة المكتبة هنا
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/compare.svg

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/App_icon.png" # للأجهزة القديمة و iOS
  
  # ضروري جداً للأندرويد الحديث
  adaptive_icon_background: "#000000" 
  adaptive_icon_foreground: "assets/images/App_icon.png"